/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateIntegrationRequest {
    /// The name of your integration. This name can be anything that makes sense for your organization (eg. Twilio SendGrid)
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    /// Indicates if the integration is enabled.
    #[serde(rename = "enabled", deserialize_with = "Option::deserialize")]
    pub enabled: Option<serde_json::Value>,
    /// The IdP's SAML POST endpoint. This endpoint should receive requests and initiate an SSO login flow. This is called the \"Embed Link\" in the Twilio SendGrid UI.
    #[serde(rename = "signin_url", deserialize_with = "Option::deserialize")]
    pub signin_url: Option<serde_json::Value>,
    /// This URL is relevant only for an IdP-initiated authentication flow. If a user authenticates from their IdP, this URL will return them to their IdP when logging out.
    #[serde(rename = "signout_url", deserialize_with = "Option::deserialize")]
    pub signout_url: Option<serde_json::Value>,
    /// An identifier provided by your IdP to identify Twilio SendGrid in the SAML interaction. This is called the \"SAML Issuer ID\" in the Twilio SendGrid UI.
    #[serde(rename = "entity_id", deserialize_with = "Option::deserialize")]
    pub entity_id: Option<serde_json::Value>,
    /// Indicates if the integration is complete.
    #[serde(rename = "completed_integration", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub completed_integration: Option<Option<serde_json::Value>>,
}

impl CreateIntegrationRequest {
    pub fn new(name: Option<serde_json::Value>, enabled: Option<serde_json::Value>, signin_url: Option<serde_json::Value>, signout_url: Option<serde_json::Value>, entity_id: Option<serde_json::Value>) -> CreateIntegrationRequest {
        CreateIntegrationRequest {
            name,
            enabled,
            signin_url,
            signout_url,
            entity_id,
            completed_integration: None,
        }
    }
}


