/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DomainAuthenticationDomainSpfDns : The DNS records for this authenticated domain.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DomainAuthenticationDomainSpfDns {
    #[serde(rename = "mail_server")]
    pub mail_server: Box<crate::models::DomainAuthenticationDomainSpfDnsMailServer>,
    #[serde(rename = "subdomain_spf")]
    pub subdomain_spf: Box<crate::models::DomainAuthenticationDomainSpfDnsSubdomainSpf>,
    #[serde(rename = "domain_spf")]
    pub domain_spf: Box<crate::models::DomainAuthenticationDomainSpfDnsDomainSpf>,
    #[serde(rename = "dkim")]
    pub dkim: Box<crate::models::DomainAuthenticationDomainSpfDnsDkim>,
}

impl DomainAuthenticationDomainSpfDns {
    /// The DNS records for this authenticated domain.
    pub fn new(mail_server: crate::models::DomainAuthenticationDomainSpfDnsMailServer, subdomain_spf: crate::models::DomainAuthenticationDomainSpfDnsSubdomainSpf, domain_spf: crate::models::DomainAuthenticationDomainSpfDnsDomainSpf, dkim: crate::models::DomainAuthenticationDomainSpfDnsDkim) -> DomainAuthenticationDomainSpfDns {
        DomainAuthenticationDomainSpfDns {
            mail_server: Box::new(mail_server),
            subdomain_spf: Box::new(subdomain_spf),
            domain_spf: Box::new(domain_spf),
            dkim: Box::new(dkim),
        }
    }
}


