/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EnforcedTlsRequestResponse {
    /// Indicates if you want to require your recipients to support TLS. 
    #[serde(rename = "require_tls", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub require_tls: Option<Option<serde_json::Value>>,
    /// Indicates if you want to require your recipients to have a valid certificate.
    #[serde(rename = "require_valid_cert", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub require_valid_cert: Option<Option<serde_json::Value>>,
}

impl EnforcedTlsRequestResponse {
    pub fn new() -> EnforcedTlsRequestResponse {
        EnforcedTlsRequestResponse {
            require_tls: None,
            require_valid_cert: None,
        }
    }
}


