/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetMcContactsCount200Response {
    /// The total number of contacts.
    #[serde(rename = "contact_count", deserialize_with = "Option::deserialize")]
    pub contact_count: Option<serde_json::Value>,
    /// The count of contacts this month for billing purposes.
    #[serde(rename = "billable_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub billable_count: Option<Option<serde_json::Value>>,
    #[serde(rename = "billable_breakdown", skip_serializing_if = "Option::is_none")]
    pub billable_breakdown: Option<Box<crate::models::GetMcContactsCount200ResponseBillableBreakdown>>,
}

impl GetMcContactsCount200Response {
    pub fn new(contact_count: Option<serde_json::Value>) -> GetMcContactsCount200Response {
        GetMcContactsCount200Response {
            contact_count,
            billable_count: None,
            billable_breakdown: None,
        }
    }
}


