/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// LinkBranding200ResponseDnsDomainCname : The DNS record generated to point to your link branding subdomain.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkBranding200ResponseDnsDomainCname {
    /// Indicates if the DNS record is valid.
    #[serde(rename = "valid", deserialize_with = "Option::deserialize")]
    pub valid: Option<Valid>,
    /// The type of DNS record that was generated.
    #[serde(rename = "type", deserialize_with = "Option::deserialize")]
    pub r#type: Option<RHashType>,
    /// The domain that this link branding will use for the links in your email.
    #[serde(rename = "host", deserialize_with = "Option::deserialize")]
    pub host: Option<serde_json::Value>,
    /// The domain that the DNS record points to.
    #[serde(rename = "data", deserialize_with = "Option::deserialize")]
    pub data: Option<serde_json::Value>,
}

impl LinkBranding200ResponseDnsDomainCname {
    /// The DNS record generated to point to your link branding subdomain.
    pub fn new(valid: Option<Valid>, r#type: Option<RHashType>, host: Option<serde_json::Value>, data: Option<serde_json::Value>) -> LinkBranding200ResponseDnsDomainCname {
        LinkBranding200ResponseDnsDomainCname {
            valid,
            r#type,
            host,
            data,
        }
    }
}

/// Indicates if the DNS record is valid.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Valid {
    #[serde(rename = "true")]
    True,
    #[serde(rename = "false")]
    False,
}

impl Default for Valid {
    fn default() -> Valid {
        Self::True
    }
}
/// The type of DNS record that was generated.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RHashType {
    #[serde(rename = "cname")]
    Cname,
    #[serde(rename = "txt")]
    Txt,
    #[serde(rename = "mx")]
    Mx,
}

impl Default for RHashType {
    fn default() -> RHashType {
        Self::Cname
    }
}

