/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PatchMailSettingsTemplateRequest {
    /// Indicates if you want to enable the legacy email template mail setting.
    #[serde(rename = "enabled", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<Option<serde_json::Value>>,
    /// The new HTML content for your legacy email template.
    #[serde(rename = "html_content", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub html_content: Option<Option<serde_json::Value>>,
}

impl PatchMailSettingsTemplateRequest {
    pub fn new() -> PatchMailSettingsTemplateRequest {
        PatchMailSettingsTemplateRequest {
            enabled: None,
            html_content: None,
        }
    }
}


