/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostWhitelabelDomainsRequest {
    /// Domain being authenticated.
    #[serde(rename = "domain", deserialize_with = "Option::deserialize")]
    pub domain: Option<serde_json::Value>,
    /// The subdomain to use for this authenticated domain.
    #[serde(rename = "subdomain", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub subdomain: Option<Option<serde_json::Value>>,
    /// The username associated with this domain.
    #[serde(rename = "username", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub username: Option<Option<serde_json::Value>>,
    /// The IP addresses that will be included in the custom SPF record for this authenticated domain.
    #[serde(rename = "ips", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ips: Option<Option<serde_json::Value>>,
    /// Specify whether to use a custom SPF or allow SendGrid to manage your SPF. This option is only available to authenticated domains set up for manual security.
    #[serde(rename = "custom_spf", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_spf: Option<Option<serde_json::Value>>,
    /// Whether to use this authenticated domain as the fallback if no authenticated domains match the sender's domain.
    #[serde(rename = "default", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default: Option<Option<serde_json::Value>>,
    /// Whether to allow SendGrid to manage your SPF records, DKIM keys, and DKIM key rotation.
    #[serde(rename = "automatic_security", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub automatic_security: Option<Option<serde_json::Value>>,
    /// Add a custom DKIM selector. Accepts three letters or numbers.
    #[serde(rename = "custom_dkim_selector", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub custom_dkim_selector: Option<Option<serde_json::Value>>,
}

impl PostWhitelabelDomainsRequest {
    pub fn new(domain: Option<serde_json::Value>) -> PostWhitelabelDomainsRequest {
        PostWhitelabelDomainsRequest {
            domain,
            subdomain: None,
            username: None,
            ips: None,
            custom_spf: None,
            default: None,
            automatic_security: None,
            custom_dkim_selector: None,
        }
    }
}


