/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostTemplatesRequest {
    /// The name for the new transactional template.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    /// Defines whether the template supports dynamic replacement.
    #[serde(rename = "generation", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub generation: Option<Option<Generation>>,
}

impl PostTemplatesRequest {
    pub fn new(name: Option<serde_json::Value>) -> PostTemplatesRequest {
        PostTemplatesRequest {
            name,
            generation: None,
        }
    }
}

/// Defines whether the template supports dynamic replacement.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Generation {
    #[serde(rename = "legacy")]
    Legacy,
    #[serde(rename = "dynamic")]
    Dynamic,
}

impl Default for Generation {
    fn default() -> Generation {
        Self::Legacy
    }
}

