/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostMcContactsExportsRequest {
    /// IDs of the contact lists you want to export.
    #[serde(rename = "list_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub list_ids: Option<Option<serde_json::Value>>,
    /// IDs of the contact segments you want to export.
    #[serde(rename = "segment_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub segment_ids: Option<Option<serde_json::Value>>,
    #[serde(rename = "notifications", skip_serializing_if = "Option::is_none")]
    pub notifications: Option<Box<crate::models::PostMcContactsExportsRequestNotifications>>,
    /// File type for export file. Choose from `json` or `csv`.
    #[serde(rename = "file_type", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub file_type: Option<Option<FileType>>,
    /// The maximum size of an export file in MB. Note that when this option is specified, multiple output files may be returned from the export.
    #[serde(rename = "max_file_size", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub max_file_size: Option<Option<serde_json::Value>>,
}

impl PostMcContactsExportsRequest {
    pub fn new() -> PostMcContactsExportsRequest {
        PostMcContactsExportsRequest {
            list_ids: None,
            segment_ids: None,
            notifications: None,
            file_type: None,
            max_file_size: None,
        }
    }
}

/// File type for export file. Choose from `json` or `csv`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileType {
    #[serde(rename = "csv")]
    Csv,
    #[serde(rename = "json")]
    Json,
}

impl Default for FileType {
    fn default() -> FileType {
        Self::Csv
    }
}

