/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostMailSendRequestMailSettings : A collection of different mail settings that you can use to specify how you would like this email to be handled.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostMailSendRequestMailSettings {
    #[serde(rename = "bypass_list_management", skip_serializing_if = "Option::is_none")]
    pub bypass_list_management: Option<Box<crate::models::PostMailSendRequestMailSettingsBypassListManagement>>,
    #[serde(rename = "bypass_spam_management", skip_serializing_if = "Option::is_none")]
    pub bypass_spam_management: Option<Box<crate::models::PostMailSendRequestMailSettingsBypassSpamManagement>>,
    #[serde(rename = "bypass_bounce_management", skip_serializing_if = "Option::is_none")]
    pub bypass_bounce_management: Option<Box<crate::models::PostMailSendRequestMailSettingsBypassBounceManagement>>,
    #[serde(rename = "bypass_unsubscribe_management", skip_serializing_if = "Option::is_none")]
    pub bypass_unsubscribe_management: Option<Box<crate::models::PostMailSendRequestMailSettingsBypassUnsubscribeManagement>>,
    #[serde(rename = "footer", skip_serializing_if = "Option::is_none")]
    pub footer: Option<Box<crate::models::PostMailSendRequestMailSettingsFooter>>,
    #[serde(rename = "sandbox_mode", skip_serializing_if = "Option::is_none")]
    pub sandbox_mode: Option<Box<crate::models::PostMailSendRequestMailSettingsSandboxMode>>,
}

impl PostMailSendRequestMailSettings {
    /// A collection of different mail settings that you can use to specify how you would like this email to be handled.
    pub fn new() -> PostMailSendRequestMailSettings {
        PostMailSendRequestMailSettings {
            bypass_list_management: None,
            bypass_spam_management: None,
            bypass_bounce_management: None,
            bypass_unsubscribe_management: None,
            footer: None,
            sandbox_mode: None,
        }
    }
}


