/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostMailSendRequestTrackingSettings : Settings to determine how you would like to track the metrics of how your recipients interact with your email.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostMailSendRequestTrackingSettings {
    #[serde(rename = "click_tracking", skip_serializing_if = "Option::is_none")]
    pub click_tracking: Option<Box<crate::models::PostMailSendRequestTrackingSettingsClickTracking>>,
    #[serde(rename = "open_tracking", skip_serializing_if = "Option::is_none")]
    pub open_tracking: Option<Box<crate::models::PostMailSendRequestTrackingSettingsOpenTracking>>,
    #[serde(rename = "subscription_tracking", skip_serializing_if = "Option::is_none")]
    pub subscription_tracking: Option<Box<crate::models::PostMailSendRequestTrackingSettingsSubscriptionTracking>>,
    #[serde(rename = "ganalytics", skip_serializing_if = "Option::is_none")]
    pub ganalytics: Option<Box<crate::models::PostMailSendRequestTrackingSettingsGanalytics>>,
}

impl PostMailSendRequestTrackingSettings {
    /// Settings to determine how you would like to track the metrics of how your recipients interact with your email.
    pub fn new() -> PostMailSendRequestTrackingSettings {
        PostMailSendRequestTrackingSettings {
            click_tracking: None,
            open_tracking: None,
            subscription_tracking: None,
            ganalytics: None,
        }
    }
}


