/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// PostMailSendRequestTrackingSettingsSubscriptionTracking : Allows you to insert a subscription management link at the bottom of the text and HTML bodies of your email. If you would like to specify the location of the link within your email, you may use the `substitution_tag`.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostMailSendRequestTrackingSettingsSubscriptionTracking {
    /// Indicates if this setting is enabled.
    #[serde(rename = "enable", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub enable: Option<Option<serde_json::Value>>,
    /// Text to be appended to the email with the subscription tracking link. You may control where the link is by using the tag <% %>
    #[serde(rename = "text", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub text: Option<Option<serde_json::Value>>,
    /// HTML to be appended to the email with the subscription tracking link. You may control where the link is by using the tag <% %>
    #[serde(rename = "html", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub html: Option<Option<serde_json::Value>>,
    /// A tag that will be replaced with the unsubscribe URL. for example: `[unsubscribe_url]`. If this parameter is used, it will override both the `text` and `html` parameters. The URL of the link will be placed at the substitution tag’s location with no additional formatting.
    #[serde(rename = "substitution_tag", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub substitution_tag: Option<Option<serde_json::Value>>,
}

impl PostMailSendRequestTrackingSettingsSubscriptionTracking {
    /// Allows you to insert a subscription management link at the bottom of the text and HTML bodies of your email. If you would like to specify the location of the link within your email, you may use the `substitution_tag`.
    pub fn new() -> PostMailSendRequestTrackingSettingsSubscriptionTracking {
        PostMailSendRequestTrackingSettingsSubscriptionTracking {
            enable: None,
            text: None,
            html: None,
            substitution_tag: None,
        }
    }
}


