/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostV3Teammates201Response {
    /// Token to identify invite
    #[serde(rename = "token", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub token: Option<Option<serde_json::Value>>,
    /// Teammate's email address
    #[serde(rename = "email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub email: Option<Option<serde_json::Value>>,
    /// Initial set of permissions to give to teammate if they accept the invite
    #[serde(rename = "scopes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scopes: Option<Option<serde_json::Value>>,
    /// Set to true if teammate should have admin privileges
    #[serde(rename = "is_admin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub is_admin: Option<Option<serde_json::Value>>,
}

impl PostV3Teammates201Response {
    pub fn new() -> PostV3Teammates201Response {
        PostV3Teammates201Response {
            token: None,
            email: None,
            scopes: None,
            is_admin: None,
        }
    }
}


