/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostV3TeammatesRequest {
    /// New teammate's email
    #[serde(rename = "email", deserialize_with = "Option::deserialize")]
    pub email: Option<serde_json::Value>,
    /// Set to specify list of scopes that teammate should have. Should be empty if teammate is an admin.
    #[serde(rename = "scopes", deserialize_with = "Option::deserialize")]
    pub scopes: Option<serde_json::Value>,
    /// Set to true if teammate should be an admin user
    #[serde(rename = "is_admin", deserialize_with = "Option::deserialize")]
    pub is_admin: Option<serde_json::Value>,
}

impl PostV3TeammatesRequest {
    pub fn new(email: Option<serde_json::Value>, scopes: Option<serde_json::Value>, is_admin: Option<serde_json::Value>) -> PostV3TeammatesRequest {
        PostV3TeammatesRequest {
            email,
            scopes,
            is_admin,
        }
    }
}


