/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PostWhitelabelLinksIdValidate200Response {
    /// The ID of the branded link.
    #[serde(rename = "id", deserialize_with = "Option::deserialize")]
    pub id: Option<serde_json::Value>,
    /// Indicates if the link branding is valid.
    #[serde(rename = "valid", deserialize_with = "Option::deserialize")]
    pub valid: Option<Valid>,
    #[serde(rename = "validation_results")]
    pub validation_results: Box<crate::models::PostWhitelabelLinksIdValidate200ResponseValidationResults>,
}

impl PostWhitelabelLinksIdValidate200Response {
    pub fn new(id: Option<serde_json::Value>, valid: Option<Valid>, validation_results: crate::models::PostWhitelabelLinksIdValidate200ResponseValidationResults) -> PostWhitelabelLinksIdValidate200Response {
        PostWhitelabelLinksIdValidate200Response {
            id,
            valid,
            validation_results: Box::new(validation_results),
        }
    }
}

/// Indicates if the link branding is valid.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Valid {
    #[serde(rename = "true")]
    True,
    #[serde(rename = "false")]
    False,
}

impl Default for Valid {
    fn default() -> Valid {
        Self::True
    }
}

