/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutMcContactsImports200Response {
    /// The ID of the import job.
    #[serde(rename = "job_id", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub job_id: Option<Option<serde_json::Value>>,
    /// The URI to PUT the upload file to.
    #[serde(rename = "upload_uri", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upload_uri: Option<Option<serde_json::Value>>,
    /// A list of headers that must be included in PUT request.
    #[serde(rename = "upload_headers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub upload_headers: Option<Option<serde_json::Value>>,
}

impl PutMcContactsImports200Response {
    pub fn new() -> PutMcContactsImports200Response {
        PutMcContactsImports200Response {
            job_id: None,
            upload_uri: None,
            upload_headers: None,
        }
    }
}


