/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutMarketingSinglesendsIdSchedule201Response {
    /// 
    #[serde(rename = "send_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub send_at: Option<Option<serde_json::Value>>,
    #[serde(rename = "status", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub status: Option<Option<Status>>,
}

impl PutMarketingSinglesendsIdSchedule201Response {
    pub fn new() -> PutMarketingSinglesendsIdSchedule201Response {
        PutMarketingSinglesendsIdSchedule201Response {
            send_at: None,
            status: None,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Status {
    #[serde(rename = "scheduled")]
    Scheduled,
}

impl Default for Status {
    fn default() -> Status {
        Self::Scheduled
    }
}

