/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct PutMarketingSinglesendsIdScheduleRequest {
    /// This is the ISO 8601 time at which to send the Single Send; must be in future, or the string \"now\"
    #[serde(rename = "send_at", deserialize_with = "Option::deserialize")]
    pub send_at: Option<serde_json::Value>,
}

impl PutMarketingSinglesendsIdScheduleRequest {
    pub fn new(send_at: Option<serde_json::Value>) -> PutMarketingSinglesendsIdScheduleRequest {
        PutMarketingSinglesendsIdScheduleRequest {
            send_at,
        }
    }
}


