/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

/// SegmentStatusResponse : Segment status indicates whether the segment's contacts will be updated periodically



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SegmentStatusResponse {
    /// Status of query validation. PENDING, VALID, or INVALID
    #[serde(rename = "query_validation", deserialize_with = "Option::deserialize")]
    pub query_validation: Option<serde_json::Value>,
    /// Describes any errors that were encountered during query validation
    #[serde(rename = "error_message", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<Option<serde_json::Value>>,
}

impl SegmentStatusResponse {
    /// Segment status indicates whether the segment's contacts will be updated periodically
    pub fn new(query_validation: Option<serde_json::Value>) -> SegmentStatusResponse {
        SegmentStatusResponse {
            query_validation,
            error_message: None,
        }
    }
}


