/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SegmentQueryJsonContacts {
    #[serde(rename = "op", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub op: Option<Option<serde_json::Value>>,
    #[serde(rename = "l", skip_serializing_if = "Option::is_none")]
    pub l: Option<Box<crate::models::SegmentQueryJsonContactsL>>,
    #[serde(rename = "r", skip_serializing_if = "Option::is_none")]
    pub r: Option<Box<crate::models::SegmentQueryJsonContactsR>>,
}

impl SegmentQueryJsonContacts {
    pub fn new() -> SegmentQueryJsonContacts {
        SegmentQueryJsonContacts {
            op: None,
            l: None,
            r: None,
        }
    }
}


