/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SinglesendRequestSendTo {
    /// The recipient List IDs that will receive the Single Send.
    #[serde(rename = "list_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub list_ids: Option<Option<serde_json::Value>>,
    /// The recipient Segment IDs that will receive the Single Send.
    #[serde(rename = "segment_ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub segment_ids: Option<Option<serde_json::Value>>,
    /// Set to `true` to send to All Contacts. If set to `false`, at least one `list_ids` or `segment_ids` value must be provided before the Single Send is scheduled to be sent to recipients.
    #[serde(rename = "all", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub all: Option<Option<serde_json::Value>>,
}

impl SinglesendRequestSendTo {
    pub fn new() -> SinglesendRequestSendTo {
        SinglesendRequestSendTo {
            list_ids: None,
            segment_ids: None,
            all: None,
        }
    }
}


