/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SinglesendRequest {
    /// The name of the Single Send.
    #[serde(rename = "name", deserialize_with = "Option::deserialize")]
    pub name: Option<serde_json::Value>,
    /// The categories to associate with this Single Send.
    #[serde(rename = "categories", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub categories: Option<Option<serde_json::Value>>,
    /// The ISO 8601 time at which to send the Single Send — this must be set for a future time.
    #[serde(rename = "send_at", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub send_at: Option<Option<serde_json::Value>>,
    #[serde(rename = "send_to", skip_serializing_if = "Option::is_none")]
    pub send_to: Option<Box<crate::models::SinglesendRequestSendTo>>,
    #[serde(rename = "email_config", skip_serializing_if = "Option::is_none")]
    pub email_config: Option<Box<crate::models::SinglesendRequestEmailConfig>>,
}

impl SinglesendRequest {
    pub fn new(name: Option<serde_json::Value>) -> SinglesendRequest {
        SinglesendRequest {
            name,
            categories: None,
            send_at: None,
            send_to: None,
            email_config: None,
        }
    }
}


