/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SingleContactRequestContact {
    #[serde(rename = "primary_email", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub primary_email: Option<Option<serde_json::Value>>,
    #[serde(rename = "alternate_emails", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub alternate_emails: Option<Option<serde_json::Value>>,
    #[serde(rename = "first_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub first_name: Option<Option<serde_json::Value>>,
    #[serde(rename = "last_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub last_name: Option<Option<serde_json::Value>>,
    #[serde(rename = "address_line_1", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address_line_1: Option<Option<serde_json::Value>>,
    #[serde(rename = "address_line_2", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub address_line_2: Option<Option<serde_json::Value>>,
    #[serde(rename = "city", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub city: Option<Option<serde_json::Value>>,
    #[serde(rename = "state_province_region", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub state_province_region: Option<Option<serde_json::Value>>,
    #[serde(rename = "postal_code", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub postal_code: Option<Option<serde_json::Value>>,
    #[serde(rename = "country", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub country: Option<Option<serde_json::Value>>,
    #[serde(rename = "custom_fields", skip_serializing_if = "Option::is_none")]
    pub custom_fields: Option<Box<crate::models::SingleContactRequestContactCustomFields>>,
}

impl SingleContactRequestContact {
    pub fn new() -> SingleContactRequestContact {
        SingleContactRequestContact {
            primary_email: None,
            alternate_emails: None,
            first_name: None,
            last_name: None,
            address_line_1: None,
            address_line_2: None,
            city: None,
            state_province_region: None,
            postal_code: None,
            country: None,
            custom_fields: None,
        }
    }
}


