/*
 * Email Activity (beta)
 *
 * The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data. The Beta endpoints for the new Email Activity APIs - functionality is subject to change without notice. You may not have access to this Beta endpoint.  Email Activity offers filtering and search by event type for two days worth of data. There is an optional add-on to store 60 days worth of data. This add-on also gives you access to the ability to download a CSV of the 60 days worth of email event data.
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateACampaignRequest {
    /// The title of the campaign.
    #[serde(rename = "title", deserialize_with = "Option::deserialize")]
    pub title: Option<serde_json::Value>,
    /// The subject line for your campaign.
    #[serde(rename = "subject", deserialize_with = "Option::deserialize")]
    pub subject: Option<serde_json::Value>,
    /// The categories you want to tag on this campaign.
    #[serde(rename = "categories", deserialize_with = "Option::deserialize")]
    pub categories: Option<serde_json::Value>,
    /// The HTML content of this campaign.
    #[serde(rename = "html_content", deserialize_with = "Option::deserialize")]
    pub html_content: Option<serde_json::Value>,
    /// The plain content of this campaign.
    #[serde(rename = "plain_content", deserialize_with = "Option::deserialize")]
    pub plain_content: Option<serde_json::Value>,
}

impl UpdateACampaignRequest {
    pub fn new(title: Option<serde_json::Value>, subject: Option<serde_json::Value>, categories: Option<serde_json::Value>, html_content: Option<serde_json::Value>, plain_content: Option<serde_json::Value>) -> UpdateACampaignRequest {
        UpdateACampaignRequest {
            title,
            subject,
            categories,
            html_content,
            plain_content,
        }
    }
}


